# Cleaning of FIFA 21 Dataset

In the Inspect_Strategize file, the columns of this dataset were grouped and guidelines on how to deal with the data in each group was noted. This file will aim to follow these guidelines but will not insist on them.

In [50]:
# Imports

import pandas as pd
import numpy as np
import re
import datetime as dt

In [2]:
# Load dataframe

rawfifa = pd.read_csv(r"C:\Users\T. Barnes\Documents\Data Science\DataCleaningChallenge\Working_on\fifa21 raw data v2.csv")
rawfifa.head()

C:\Users\T. Barnes\AppData\Local\Temp\ipykernel_17860\3557960164.py:3: DtypeWarning: Columns (76) have mixed types. Specify dtype option on import or set low_memory=False.
  rawfifa = pd.read_csv(r"C:\Users\T. Barnes\Documents\Data Science\DataCleaningChallenge\Working_on\fifa21 raw data v2.csv")

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,91,\n\n\n\nManchester City,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,91,\n\n\n\nParis Saint-Germain,...,High,Medium,5 ★,91,85,86,94,36,59,595

In [4]:
# Modify column names

rawfifa.columns = [re.sub("[^a-zA-Z]", "_", x).strip().strip("_").lower() for x in rawfifa.columns]
rawfifa.columns

Index(['id', 'name', 'longname', 'photourl', 'playerurl', 'nationality', 'age',
       'ova', 'pot', 'club', 'contract', 'positions', 'height', 'weight',
       'preferred_foot', 'bov', 'best_position', 'joined', 'loan_date_end',
       'value', 'wage', 'release_clause', 'attacking', 'crossing', 'finishing',
       'heading_accuracy', 'short_passing', 'volleys', 'skill', 'dribbling',
       'curve', 'fk_accuracy', 'long_passing', 'ball_control', 'movement',
       'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance',
       'power', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots',
       'mentality', 'aggression', 'interceptions', 'positioning', 'vision',
       'penalties', 'composure', 'defending', 'marking', 'standing_tackle',
       'sliding_tackle', 'goalkeeping', 'gk_diving', 'gk_handling',
       'gk_kicking', 'gk_positioning', 'gk_reflexes', 'total_stats',
       'base_stats', 'w_f', 'sm', 'a_w', 'd_w', 'ir', 'pac', 'sho', 'pas',
       'dri', 'def', 'phy', 'hits'],
      dtype='object')

# Changes by Column



## id

* Change type to string
* check that values are unique

In [9]:
# Change types to string

rawfifa['id'] = [str(x) for x in rawfifa.id]

In [11]:
# Check uniqueness

rawfifa[rawfifa.duplicated(subset='id')]

Empty DataFrame
Columns: [id, name, longname, photourl, playerurl, nationality, age, ova, pot, club, contract, positions, height, weight, preferred_foot, bov, best_position, joined, loan_date_end, value, wage, release_clause, attacking, crossing, finishing, heading_accuracy, short_passing, volleys, skill, dribbling, curve, fk_accuracy, long_passing, ball_control, movement, acceleration, sprint_speed, agility, reactions, balance, power, shot_power, jumping, stamina, strength, long_shots, mentality, aggression, interceptions, positioning, vision, penalties, composure, defending, marking, standing_tackle, sliding_tackle, goalkeeping, gk_diving, gk_handling, gk_kicking, gk_positioning, gk_reflexes, total_stats, base_stats, w_f, sm, a_w, d_w, ir, pac, sho, pas, dri, def, phy, hits]
Index: []

[0 rows x 77 columns]

Subset of duplicates returns an empty table. So the column is clean

## photourl and playerurl

* check for unique values

In [13]:
# Check uniqueness

rawfifa[rawfifa.duplicated(subset='playerurl')]

Empty DataFrame
Columns: [id, name, longname, photourl, playerurl, nationality, age, ova, pot, club, contract, positions, height, weight, preferred_foot, bov, best_position, joined, loan_date_end, value, wage, release_clause, attacking, crossing, finishing, heading_accuracy, short_passing, volleys, skill, dribbling, curve, fk_accuracy, long_passing, ball_control, movement, acceleration, sprint_speed, agility, reactions, balance, power, shot_power, jumping, stamina, strength, long_shots, mentality, aggression, interceptions, positioning, vision, penalties, composure, defending, marking, standing_tackle, sliding_tackle, goalkeeping, gk_diving, gk_handling, gk_kicking, gk_positioning, gk_reflexes, total_stats, base_stats, w_f, sm, a_w, d_w, ir, pac, sho, pas, dri, def, phy, hits]
Index: []

[0 rows x 77 columns]

In [14]:

rawfifa[rawfifa.duplicated(subset='photourl')]

Empty DataFrame
Columns: [id, name, longname, photourl, playerurl, nationality, age, ova, pot, club, contract, positions, height, weight, preferred_foot, bov, best_position, joined, loan_date_end, value, wage, release_clause, attacking, crossing, finishing, heading_accuracy, short_passing, volleys, skill, dribbling, curve, fk_accuracy, long_passing, ball_control, movement, acceleration, sprint_speed, agility, reactions, balance, power, shot_power, jumping, stamina, strength, long_shots, mentality, aggression, interceptions, positioning, vision, penalties, composure, defending, marking, standing_tackle, sliding_tackle, goalkeeping, gk_diving, gk_handling, gk_kicking, gk_positioning, gk_reflexes, total_stats, base_stats, w_f, sm, a_w, d_w, ir, pac, sho, pas, dri, def, phy, hits]
Index: []

[0 rows x 77 columns]

No duplicates

## nationality

* get unique values
* check for variations in value representations

In [22]:
# Get unique values

countries = list(rawfifa.nationality.sort_values().unique())

In [23]:
countries

['Afghanistan',
 'Albania',
 'Algeria',
 'Andorra',
 'Angola',
 'Antigua & Barbuda',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bolivia',
 'Bosnia Herzegovina',
 'Brazil',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Central African Republic',
 'Chad',
 'Chile',
 'China PR',
 'Chinese Taipei',
 'Colombia',
 'Comoros',
 'Congo',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Curacao',
 'Cyprus',
 'Czech Republic',
 'DR Congo',
 'Denmark',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'England',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Ethiopia',
 'Faroe Islands',
 'Finland',
 'France',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Grenada',
 'Guam',
 'Guatemala',
 'Guinea',
 'Guinea Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hong Kong',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Israel',
 'Italy',
 'Ivory Coast',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Korea DPR',
 'Korea Republic',
 'Kosovo',
 'Latvia',
 'Lebanon',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Macau',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Mali',
 'Malta',
 'Mauritania',
 'Mexico',
 'Moldova',
 'Montenegro',
 'Montserrat',
 'Morocco',
 'Mozambique',
 'Namibia',
 'Netherlands',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Macedonia',
 'Northern Ireland',
 'Norway',
 'Palestine',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Republic of Ireland',
 'Romania',
 'Russia',
 'Rwanda',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saudi Arabia',
 'Scotland',
 'Senegal',
 'Serbia',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'South Africa',
 'South Sudan',
 'Spain',
 'Sudan',
 'Sweden',
 'Switzerland',
 'Syria',
 'São Tomé & Príncipe',
 'Tanzania',
 'Thailand',
 'Togo',
 'Trinidad & Tobago',
 'Tunisia',
 'Turkey',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United States',
 'Uruguay',
 'Uzbekistan',
 'Venezuela',
 'Wales',
 'Zambia',
 'Zimbabwe']

nationality column looks okay

## age, ova, pot, bo columns

* checking for impossible values

In [32]:
rawfifa[["age", "ova", "pot", "bov"]].describe()

                age           ova           pot           bov
count  18979.000000  18979.000000  18979.000000  18979.000000
mean      25.194109     65.718636     71.136414     66.751726
std        4.710520      6.968999      6.114635      6.747193
min       16.000000     47.000000     47.000000     48.000000
25%       21.000000     61.000000     67.000000     62.000000
50%       25.000000     66.000000     71.000000     67.000000
75%       29.000000     70.000000     75.000000     71.000000
max       53.000000     93.000000     95.000000     93.000000

From the above table, I can tell that all values fall under an acceptable range.

## club
* uniformity of values

In [43]:
# Get unique values

clubs = list(rawfifa.club.sort_values().unique())
len(clubs)

682

In [44]:
for x in clubs:
    print(x)

1. FC Heidenheim 1846
1. FC Kaiserslautern
1. FC Köln
1. FC Magdeburg
1. FC Nürnberg
1. FC Saarbrücken
1. FC Union Berlin
1. FSV Mainz 05
AC Ajaccio
AC Horsens
AC Mineros de Guayana
AC Monza
AD Alcorcón
ADO Den Haag
AEK Athens
AFC Wimbledon
AIK
AJ Auxerre
AS Monaco
AS Nancy Lorraine
AS Saint-Étienne
AZ Alkmaar
Aalborg BK
Aalesunds FK
Aarhus GF
Aberdeen
Abha Club
Academica Clinceni
Accrington Stanley
Adelaide United
Ajax
Al Adalah
Al Ahli
Al Ain FC
Al Faisaly
Al Fateh
Al Fayha
Al Hazem
Al Hilal
Al Ittihad
Al Nassr
Al Raed
Al Shabab
Al Taawoun
Al Wehda
Alanyaspor
Albacete BP
Alianza Lima
Always Ready
Amiens SC
América de Cali
Angers SCO
Antalyaspor
Aragua FC
Argentinos Juniors
Arsenal
Arsenal de Sarandí
Aston Villa
Astra Giurgiu
Atalanta
Athletic Club de Bilbao
Atiker Konyaspor
Atlanta United
Atlético Clube Goianiense
Atlético Madrid
Atlético Mineiro
Atlético Nacional
Atlético Tucumán
Atlético de San Luis
Audax Italiano
BB Erzurumspor
BK Häcken
BSC Young Boys
Bahia
Barcelona Sporting Club
Barnsley
Barrow
Bayer 04 Leverkusen
Bayern München II
Beerschot AC
Beijing Sinobo Guoan FC
Benevento
Beşiktaş JK
Birmingham City
Blackburn Rovers
Blackpool
Boavista FC
Boca Juniors
Bohemian FC
Bologna
Bolton Wanderers
Borussia Dortmund
Borussia Mönchengladbach
Botafogo
Bournemouth
Bradford City
Brentford
Brescia
Brighton & Hove Albion
Brisbane Roar
Bristol City
Bristol Rovers
Brøndby IF
Burnley
Burton Albion
Busan IPark
C.D. Castellón
CA Osasuna
CD Huachipato
CD Leganés
CD Lugo
CD Mirandés
CD Nacional
CD Tenerife
CD Tondela
CE Sabadell FC
CF Fuenlabrada
CFR Cluj
Cagliari
Cambridge United
Caracas FC
Cardiff City
Carlisle United
Ceará Sporting Club
Celtic
Central Coast Mariners
Central Córdoba
Centro Atlético Fénix
Cerezo Osaka
Chamois Niortais Football Club
Charlton Athletic
Chelsea
Cheltenham Town
Chicago Fire
Chievo Verona
Chindia Târgovişte
Chongqing Dangdai Lifan FC SWM Team
Clermont Foot 63
Club América
Club Athletico Paranaense
Club Atlas
Club Atlético Aldosivi
Club Atlético Banfield
Club Atlético Colón
Club Atlético Grau
Club Atlético Huracán
Club Atlético Lanús
Club Atlético Talleres
Club Atlético Tigre
Club Blooming
Club Bolívar
Club Brugge KV
Club Guaraní
Club León
Club Libertad
Club Necaxa
Club Plaza Colonia
Club Tijuana
Clube Sport Marítimo
Colchester United
Colo-Colo
Colorado Rapids
Columbus Crew SC
Coquimbo Unido
Coritiba
Cork City
Coventry City
Cracovia
Crawley Town
Crewe Alexandra
Crotone
Cruz Azul
Crystal Palace
Cusco FC
Cádiz CF
DC United
DSC Arminia Bielefeld
Daegu FC
Dalian YiFang FC
Damac FC
Defensa y Justicia
Delfín SC
Denizlispor
Deportivo Alavés
Deportivo Binacional
Deportivo Cali
Deportivo Pasto
Deportivo Toluca
Derby County
Derry City
Dijon FCO
Dinamo Bucureşti
Dinamo Zagreb
Djurgårdens IF
Doncaster Rovers
Dundalk
Dundee United
Dynamo Kyiv
ESTAC Troyes
Eintracht Braunschweig
Eintracht Frankfurt
El Nacional
Elche CF
Emelec
Empoli
En Avant de Guingamp
Estudiantes de La Plata
Estudiantes de Mérida
Ettifaq FC
Everton
Exeter City
FC Admira Wacker Mödling
FC Argeș
FC Augsburg
FC Barcelona
FC Basel 1893
FC Bayern München
FC Botoşani
FC Cartagena
FC Chambly Oise
FC Cincinnati
FC Dallas
FC Emmen
FC Erzgebirge Aue
FC Girondins de Bordeaux
FC Groningen
FC Hansa Rostock
FC Hermannstadt
FC Ingolstadt 04
FC Juárez
FC København
FC Lausanne-Sport
FC Lorient
FC Lugano
FC Luzern
FC Metz
FC Midtjylland
FC Nantes
FC Nordsjælland
FC Paços de Ferreira
FC Porto
FC Red Bull Salzburg
FC Schalke 04
FC Seoul
FC Sion
FC Sochaux-Montbéliard
FC St. Gallen
FC St. Pauli
FC Tokyo
FC Twente
FC Utrecht
FC Vaduz
FC Viitorul
FC Voluntari
FC Würzburger Kickers
FC Zürich
FCSB (Steaua)
FK Austria Wien
FK Bodø/Glimt
FK Haugesund
FSV Zwickau
Falkenbergs FF
Famalicão
Farense
Fatih Karagümrük S.K.
Fenerbahçe SK
Feyenoord
Finn Harps
Fiorentina
Flamengo
Fleetwood Town
Fluminense
Forest Green Rovers
Fortaleza
Fortuna Düsseldorf
Fortuna Sittard
Fulham
Galatasaray SK
Gamba Osaka
Gangwon FC
Gaz Metan Mediaş
Gazişehir Gaziantep F.K.
Genoa
Gençlerbirliği SK
Getafe CF
Gil Vicente FC
Gillingham
Gimnasia y Esgrima La Plata
Girona FC
Godoy Cruz
Goiás
Granada CF
Grenoble Foot 38
Grimsby Town
Grêmio
Guadalajara
Guangzhou Evergrande Taobao FC
Guangzhou R&F FC
GwangJu FC
Górnik Zabrze
Göztepe SK
HJK Helsinki
Hallescher FC
Hamburger SV
Hamilton Academical FC
Hammarby IF
Hannover 96
Harrogate Town
Hatayspor
Hebei China Fortune FC
Hellas Verona
Helsingborgs IF
Henan Jianye FC
Heracles Almelo
Hertha BSC
Hibernian
Hokkaido Consadole Sapporo
Holstein Kiel
Houston Dynamo
Huddersfield Town
Hull City
IF Elfsborg
IFK Göteborg
IFK Norrköping
IK Sirius
IK Start
Incheon United FC
Independiente
Independiente Medellín
Independiente del Valle
Inter
Inter Miami
Internacional
Ipswich Town
Jagiellonia Białystok
Jeonbuk Hyundai Motors
Jiangsu Suning FC
Jorge Wilstermann
Junior FC
Juventus
KAA Gent
KAS Eupen
KFC Uerdingen 05
KRC Genk
KSV Cercle Brugge
KV Kortrijk
KV Mechelen
KV Oostende
Kaizer Chiefs
Kalmar FF
Karlsruher SC
Kashima Antlers
Kashiwa Reysol
Kasimpaşa SK
Kawasaki Frontale
Kayserispor
Kilmarnock
Kristiansund BK
LA Galaxy
LASK Linz
LDU Quito
LOSC Lille
La Berrichonne de Châteauroux
Lazio
Le Havre AC
Lecce
Lech Poznań
Lechia Gdańsk
Leeds United
Legia Warszawa
Leicester City
Levante UD
Leyton Orient
Lincoln City
Liverpool
Liverpool Fútbol Club
Livingston FC
Llaneros de Guanare
Lokomotiv Moscow
Los Angeles FC
Luton Town
Lyngby BK
MKE Ankaragücü
MSV Duisburg
Macarthur FC
Malmö FF
Manchester City
Manchester United
Mansfield Town
Mazatlán FC
Medipol Başakşehir FK
Melbourne City FC
Melbourne Victory
Melgar FBC
Middlesbrough
Milan
Millonarios FC
Millwall
Milton Keynes Dons
Minnesota United FC
Mjällby AIF
Mjøndalen IF
Molde FK
Monterrey
Montpellier HSC
Montreal Impact
Morecambe
Moreirense FC
Motherwell
Málaga CF
Nacional Asunción
Nacional Potosí
Nacional de Montevideo
Nagoya Grampus
Napoli
Nashville SC
New England Revolution
New York City FC
New York Red Bulls
Newcastle Jets
Newcastle United
Newell's Old Boys
Newport County
No Club
Northampton Town
Norwich City
Nottingham Forest
Nîmes Olympique
OGC Nice
Oceânico FC
Odds BK
Odense Boldklub
Oita Trinita
Oldham Athletic
Olimpia Asunción
Olympiacos CFP
Olympique Lyonnais
Olympique de Marseille
Oriente Petrolero
Orlando City SC
Orlando Pirates
Os Belenenses
Oud-Heverlee Leuven
Oxford United
PAOK
PEC Zwolle
PFC CSKA Moscow
PSV
Pachuca
Palmeiras
Panathinaikos FC
Paris FC
Paris Saint-Germain
Parma
Patronato
Pau FC
Perth Glory
Peterborough United
Peñarol
Philadelphia Union
Piast Gliwice
Plymouth Argyle
Podbeskidzie Bielsko-Biała
Pogoń Szczecin
Pohang Steelers
Politehnica Iaşi
Port Vale
Portimonense SC
Portland Timbers
Portsmouth
Preston North End
Puebla FC
Qingdao Huanghai F.C.
Queens Park Rangers
Querétaro
RB Leipzig
RC Celta
RC Strasbourg Alsace
RCD Espanyol
RCD Mallorca
RKC Waalwijk
RSC Anderlecht
Racing Club
Racing Club de Lens
Raków Częstochowa
Randers FC
Rangers FC
Rayo Vallecano
Reading
Real Betis
Real Madrid
Real Oviedo
Real Salt Lake
Real Sociedad
Real Sporting de Gijón
Real Valladolid CF
Real Zaragoza
Rio Ave FC
River Plate
River Plate Asunción
River Plate Montevideo
Rochdale
Rodez Aveyron Football
Roma
Rosario Central
Rosenborg BK
Ross County FC
Rotherham United
Royal Antwerp FC
Royal Excel Mouscron
SC Braga
SC Freiburg
SC Heerenveen
SC Paderborn 07
SC Verl
SCR Altach
SD Aucas
SD Eibar
SD Huesca
SD Ponferradina
SG Dynamo Dresden
SK Brann
SK Rapid Wien
SK Slavia Praha
SK Sturm Graz
SKN St. Pölten
SL Benfica
SPAL
SSV Jahn Regensburg
SV Darmstadt 98
SV Meppen
SV Ried
SV Sandhausen
SV Waldhof Mannheim
SV Wehen Wiesbaden
SV Werder Bremen
SV Zulte-Waregem
Sagan Tosu
Salford City
Sampdoria
San Jose Earthquakes
San Lorenzo de Almagro
Sandefjord Fotball
Sanfrecce Hiroshima
Sangju Sangmu FC
Santa Clara
Santos
Santos Laguna
Sarpsborg 08 FF
Sassuolo
Scunthorpe United
Seattle Sounders FC
Seongnam FC
Sepsi OSK
Servette FC
Sevilla FC
Shakhtar Donetsk
Shamrock Rovers
Shandong Luneng TaiShan FC
Shanghai Greenland Shenhua FC
Shanghai SIPG FC
Sheffield United
Sheffield Wednesday
Shelbourne FC
Shenzhen FC
Shijiazhuang Ever Bright F.C.
Shimizu S-Pulse
Shonan Bellmare
Shrewsbury
Sint-Truidense VV
Sivasspor
Sligo Rovers
Sol de América
Southampton
Southend United
SpVgg Greuther Fürth
SpVgg Unterhaching
Sparta Praha
Sparta Rotterdam
Spartak Moscow
Spezia
Sport Huancayo
Sporting CP
Sporting Kansas City
Sporting de Charleroi
Sportivo Luqueño
St. Johnstone FC
St. Mirren
St. Patrick's Athletic
Stabæk Fotball
Stade Brestois 29
Stade Malherbe Caen
Stade Rennais FC
Stade de Reims
Stal Mielec
Standard de Liège
Stevenage
Stoke City
Strømsgodset IF
Sunderland
Suwon Samsung Bluewings
Swansea City
Swindon Town
Sydney FC
São Paulo
SønderjyskE
TSG 1899 Hoffenheim
TSV 1860 München
TSV Hartberg
Tianjin TEDA FC
Tigres U.A.N.L.
Torino
Toronto FC
Tottenham Hotspur
Toulouse Football Club
Trabzonspor
Tranmere Rovers
Türkgücü München
U.N.A.M.
UD Almería
UD Las Palmas
UD Logroñés
USL Dunkerque
UTA Arad
Udinese
Ulsan Hyundai FC
Universidad Católica
Universidad Católica del Ecuador
Universitatea Craiova
Unión La Calera
Unión de Santa Fe
Urawa Red Diamonds
VVV-Venlo
Valencia CF
Valenciennes FC
Vancouver Whitecaps FC
Varbergs BoIS
Vasco da Gama
Vegalta Sendai
Vejle Boldklub
VfB Lübeck
VfB Stuttgart
VfL Bochum 1848
VfL Osnabrück
VfL Wolfsburg
Viking FK
Viktoria Köln
Viktoria Plzeň
Villarreal CF
Vissel Kobe
Vitesse
Vitória Guimarães
Vålerenga Fotball
Vélez Sarsfield
WSG Tirol
Waasland-Beveren
Walsall
Warta Poznań
Waterford FC
Watford
Wellington Phoenix
West Bromwich Albion
West Ham United
Western Sydney Wanderers
Western United FC
Wigan Athletic
Willem II
Wisła Kraków
Wisła Płock
Wolfsberger AC
Wolverhampton Wanderers
Wuhan Zall
Wycombe Wanderers
Yeni Malatyaspor
Yokohama F. Marinos
Yokohama FC
Zagłębie Lubin
Zamora FC
Çaykur Rizespor
Örebro SK
Östersunds FK
Śląsk Wrocław

In [42]:
# Remove newline character

rawfifa.club = [x.replace("\n", "") for x in rawfifa.club]
rawfifa.head()['club']

0           FC Barcelona
1               Juventus
2        Atlético Madrid
3        Manchester City
4    Paris Saint-Germain
Name: club, dtype: object

Success! Moving on

## contract, joined, loan_date_end

* check if the contract start year and joined year are the same.
* if the above is true, then the "joined" column is redundant

* also check if the contract end years and loan_date_end years are the same
* if true, then consider making loan_date_end a bool column instead

In [62]:
# convert loan_date_end and "joined" cols to dates

rawfifa.loan_date_end = pd.to_datetime(rawfifa['loan_date_end'])
rawfifa.joined = pd.to_datetime(rawfifa.joined)

In [63]:
rawfifa.joined

0       2004-07-01
1       2018-07-10
2       2014-07-16
3       2015-08-30
4       2017-08-03
           ...
18974   2018-07-13
18975   2020-08-01
18976   2019-03-08
18977   2020-09-22
18978   2019-07-29
Name: joined, Length: 18979, dtype: datetime64[ns]

In [64]:
# Split the contract column to get start and end years
contracts = [x.split("~") for x in rawfifa.contract]
contracts

[['2004 ', ' 2021'],
 ['2018 ', ' 2022'],
 ['2014 ', ' 2023'],
 ['2015 ', ' 2023'],
 ['2017 ', ' 2022'],
 ['2014 ', ' 2023'],
 ['2017 ', ' 2023'],
 ['2018 ', ' 2024'],
 ['2018 ', ' 2022'],
 ['2014 ', ' 2022'],
 ['2018 ', ' 2023'],
 ['2016 ', ' 2023'],
 ['2013 ', ' 2023'],
 ['2018 ', ' 2024'],
 ['2011 ', ' 2023'],
 ['2009 ', ' 2022'],
 ['2005 ', ' 2021'],
 ['2011 ', ' 2021'],
 ['2015 ', ' 2023'],
 ['2016 ', ' 2023'],
 ['2015 ', ' 2023'],
 ['2015 ', ' 2022'],
 ['2017 ', ' 2024'],
 ['2010 ', ' 2024'],
 ['2012 ', ' 2021'],
 ['2014 ', ' 2023'],
 ['2019 ', ' 2024'],
 ['2014 ', ' 2023'],
 ['2019 ', ' 2024'],
 ['2017 ', ' 2023'],
 ['2015 ', ' 2024'],
 ['2017 ', ' 2025'],
 ['2017 ', ' 2024'],
 ['2018 ', ' 2024'],
 ['2020 ', ' 2025'],
 ['2018 ', ' 2023'],
 ['2015 ', ' 2023'],
 ['2015 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['2005 ', ' 2021'],
 ['2008 ', ' 2023'],
 ['2018 ', ' 2023'],
 ['2017 ', ' 2024'],
 ['2015 ', ' 2021'],
 ['2012 ', ' 2021'],
 ['2020 ', ' 2022'],
 ['2012 ', ' 2022'],
 ['2016 ', ' 2025'],
 ['2008 ', ' 2023'],
 ['2011 ', ' 2023'],
 ['2013 ', ' 2022'],
 ['2011 ', ' 2022'],
 ['2012 ', ' 2024'],
 ['2016 ', ' 2021'],
 ['2012 ', ' 2023'],
 ['2008 ', ' 2022'],
 ['2019 ', ' 2022'],
 ['2014 ', ' 2023'],
 ['2020 ', ' 2022'],
 ['2014 ', ' 2022'],
 ['2012 ', ' 2024'],
 ['2011 ', ' 2023'],
 ['2019 ', ' 2024'],
 ['2015 ', ' 2024'],
 ['2017 ', ' 2021'],
 ['2020 ', ' 2025'],
 ['2019 ', ' 2024'],
 ['2017 ', ' 2023'],
 ['2014 ', ' 2023'],
 ['2015 ', ' 2021'],
 ['2017 ', ' 2023'],
 ['2020 ', ' 2025'],
 ['2020 ', ' 2025'],
 ['2018 ', ' 2023'],
 ['2013 ', ' 2024'],
 ['2018 ', ' 2023'],
 ['2018 ', ' 2023'],
 ['2020 ', ' 2025'],
 ['2020 ', ' 2024'],
 ['2020 ', ' 2024'],
 ['2019 ', ' 2024'],
 ['2010 ', ' 2022'],
 ['2015 ', ' 2023'],
 ['2020 ', ' 2021'],
 ['2011 ', ' 2024'],
 ['2018 ', ' 2023'],
 ['2019 ', ' 2024'],
 ['2015 ', ' 2023'],
 ['2020 ', ' 2024'],
 ['2017 ', ' 2024'],
 ['2020 ', ' 2024'],
 ['2015 ', ' 2023'],
 ['2018 ', ' 2024'],
 ['2013 ', ' 2022'],
 ['2016 ', ' 2025'],
 ['2020 ', ' 2023'],
 ['2016 ', ' 2021'],
 ['2020 ', ' 2024'],
 ['2012 ', ' 2023'],
 ['2017 ', ' 2024'],
 ['2013 ', ' 2023'],
 ['2015 ', ' 2022'],
 ['2019 ', ' 2024'],
 ['2014 ', ' 2024'],
 ['2018 ', ' 2023'],
 ['2020 ', ' 2024'],
 ['2020 ', ' 2024'],
 ['2015 ', ' 2023'],
 ['2016 ', ' 2023'],
 ['2020 ', ' 2024'],
 ['2017 ', ' 2022'],
 ['2016 ', ' 2023'],
 ['2015 ', ' 2024'],
 ['2019 ', ' 2022'],
 ['2018 ', ' 2022'],
 ['2013 ', ' 2026'],
 ['2020 ', ' 2024'],
 ['2019 ', ' 2024'],
 ['2018 ', ' 2022'],
 ['2019 ', ' 2024'],
 ['2016 ', ' 2022'],
 ['2018 ', ' 2023'],
 ['2015 ', ' 2023'],
 ['2017 ', ' 2022'],
 ['2020 ', ' 2022'],
 ['2013 ', ' 2023'],
 ['2013 ', ' 2022'],
 ['2010 ', ' 2021'],
 ['2019 ', ' 2023'],
 ['2015 ', ' 2022'],
 ['2015 ', ' 2023'],
 ['2018 ', ' 2022'],
 ['2018 ', ' 2023'],
 ['2013 ', ' 2021'],
 ['2017 ', ' 2022'],
 ['2012 ', ' 2022'],
 ['2017 ', ' 2022'],
 ['2011 ', ' 2023'],
 ['2018 ', ' 2022'],
 ['2018 ', ' 2022'],
 ['2020 ', ' 2021'],
 ['2017 ', ' 2021'],
 ['2020 ', ' 2025'],
 ['2019 ', ' 2025'],
 ['2017 ', ' 2022'],
 ['2019 ', ' 2024'],
 ['2019 ', ' 2023'],
 ['2019 ', ' 2024'],
 ['2017 ', ' 2022'],
 ['2019 ', ' 2023'],
 ['2020 ', ' 2024'],
 ['2020 ', ' 2025'],
 ['2015 ', ' 2024'],
 ['2015 ', ' 2023'],
 ['2020 ', ' 2025'],
 ['2019 ', ' 2024'],
 ['2018 ', ' 2025'],
 ['2019 ', ' 2024'],
 ['2016 ', ' 2025'],
 ['2018 ', ' 2023'],
 ['2016 ', ' 2023'],
 ['2016 ', ' 2024'],
 ['2018 ', ' 2024'],
 ['2012 ', ' 2022'],
 ['2019 ', ' 2023'],
 ['2012 ', ' 2023'],
 ['2015 ', ' 2024'],
 ['2019 ', ' 2025'],
 ['2015 ', ' 2022'],
 ['2018 ', ' 2021'],
 ['2011 ', ' 2021'],
 ['2016 ', ' 2023'],
 ['2018 ', ' 2023'],
 ['2019 ', ' 2024'],
 ['2014 ', ' 2022'],
 ['2020 ', ' 2023'],
 ['2019 ', ' 2024'],
 ['2020 ', ' 2023'],
 ['2019 ', ' 2022'],
 ['2018 ', ' 2023'],
 ['2020 ', ' 2021'],
 ['2019 ', ' 2022'],
 ['2013 ', ' 2022'],
 ['2011 ', ' 2023'],
 ['2015 ', ' 2023'],
 ['2016 ', ' 2024'],
 ['2018 ', ' 2023'],
 ['2017 ', ' 2022'],
 ['2015 ', ' 2023'],
 ['2019 ', ' 2024'],
 ['2018 ', ' 2023'],
 ['2009 ', ' 2024'],
 ['2018 ', ' 2023'],
 ['2017 ', ' 2024'],
 ['2015 ', ' 2024'],
 ['2018 ', ' 2023'],
 ['2016 ', ' 2023'],
 ['2019 ', ' 2024'],
 ['2019 ', ' 2023'],
 ['2018 ', ' 2022'],
 ['2020 ', ' 2023'],
 ['2020 ', ' 2022'],
 ['2015 ', ' 2022'],
 ['2018 ', ' 2022'],
 ['2007 ', ' 2022'],
 ['Jun 30, 2021 On Loan'],
 ['2020 ', ' 2023'],
 ['2020 ', ' 2023'],
 ['2017 ', ' 2024'],
 ['2020 ', ' 2021'],
 ['2018 ', ' 2022'],
 ['2018 ', ' 2022'],
 ['2020 ', ' 2021'],
 ['2016 ', ' 2021'],
 ['2019 ', ' 2024'],
 ['2017 ', ' 2023'],
 ['2017 ', ' 2021'],
 ['2017 ', ' 2022'],
 ['2019 ', ' 2023'],
 ['2020 ', ' 2025'],
 ['2019 ', ' 2024'],
 ['2019 ', ' 2024'],
 ['2017 ', ' 2023'],
 ['2017 ', ' 2023'],
 ['2018 ', ' 2022'],
 ['2017 ', ' 2022'],
 ['2015 ', ' 2023'],
 ['2020 ', ' 2024'],
 ['2020 ', ' 2025'],
 ['2015 ', ' 2022'],
 ['2019 ', ' 2024'],
 ['2015 ', ' 2022'],
 ['2019 ', ' 2024'],
 ['2018 ', ' 2024'],
 ['2020 ', ' 2024'],
 ['2017 ', ' 2022'],
 ['2015 ', ' 2023'],
 ['2015 ', ' 2022'],
 ['2019 ', ' 2022'],
 ['2014 ', ' 2024'],
 ['2020 ', ' 2024'],
 ['2018 ', ' 2023'],
 ['2018 ', ' 2021'],
 ['2019 ', ' 2023'],
 ['2019 ', ' 2024'],
 ['2018 ', ' 2022'],
 ['2016 ', ' 2023'],
 ['2020 ', ' 2024'],
 ['Jun 30, 2021 On Loan'],
 ['2012 ', ' 2022'],
 ['2019 ', ' 2023'],
 ['2018 ', ' 2022'],
 ['2019 ', ' 2023'],
 ['2020 ', ' 2022'],
 ['Jun 30, 2021 On Loan'],
 ['2020 ', ' 2023'],
 ['2017 ', ' 2022'],
 ['2018 ', ' 2023'],
 ['2011 ', ' 2023'],
 ['2014 ', ' 2023'],
 ['2014 ', ' 2022'],
 ['2009 ', ' 2021'],
 ['2019 ', ' 2021'],
 ['2019 ', ' 2023'],
 ['2019 ', ' 2022'],
 ['2013 ', ' 2021'],
 ['2017 ', ' 2024'],
 ['2020 ', ' 2024'],
 ['2020 ', ' 2023'],
 ['2019 ', ' 2022'],
 ['2011 ', ' 2021'],
 ['2020 ', ' 2021'],
 ['2011 ', ' 2021'],
 ['2015 ', ' 2022'],
 ['2016 ', ' 2023'],
 ['2019 ', ' 2024'],
 ['2020 ', ' 2023'],
 ['2020 ', ' 2023'],
 ['2019 ', ' 2024'],
 ['2020 ', ' 2025'],
 ['2019 ', ' 2026'],
 ['2019 ', ' 2025'],
 ['2020 ', ' 2024'],
 ['2017 ', ' 2023'],
 ['2019 ', ' 2025'],
 ['2019 ', ' 2023'],
 ['2018 ', ' 2024'],
 ['2019 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['Free'],
 ['2019 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['Free'],
 ['2020 ', ' 2025'],
 ['2019 ', ' 2024'],
 ['2020 ', ' 2024'],
 ['2017 ', ' 2021'],
 ['2018 ', ' 2023'],
 ['2015 ', ' 2024'],
 ['2018 ', ' 2022'],
 ['2014 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['Jun 30, 2021 On Loan'],
 ['2018 ', ' 2024'],
 ['2018 ', ' 2023'],
 ['2020 ', ' 2025'],
 ['Jun 30, 2021 On Loan'],
 ['2012 ', ' 2028'],
 ['2017 ', ' 2024'],
 ['2019 ', ' 2023'],
 ['2016 ', ' 2023'],
 ['2018 ', ' 2024'],
 ['2016 ', ' 2023'],
 ['2018 ', ' 2023'],
 ['2018 ', ' 2024'],
 ['2018 ', ' 2023'],
 ['2019 ', ' 2024'],
 ['2018 ', ' 2023'],
 ['2018 ', ' 2024'],
 ['2017 ', ' 2021'],
 ['2019 ', ' 2024'],
 ['2018 ', ' 2022'],
 ['2017 ', ' 2022'],
 ['2018 ', ' 2023'],
 ['2017 ', ' 2023'],
 ['2017 ', ' 2023'],
 ['2014 ', ' 2024'],
 ['2017 ', ' 2022'],
 ['2016 ', ' 2021'],
 ['2017 ', ' 2024'],
 ['2015 ', ' 2022'],
 ['2020 ', ' 2022'],
 ['Jun 30, 2021 On Loan'],
 ['2010 ', ' 2023'],
 ['2020 ', ' 2025'],
 ['2017 ', ' 2022'],
 ['Jun 30, 2021 On Loan'],
 ['2020 ', ' 2024'],
 ['2020 ', ' 2024'],
 ['2020 ', ' 2025'],
 ['2017 ', ' 2022'],
 ['2019 ', ' 2023'],
 ['2019 ', ' 2024'],
 ['2020 ', ' 2024'],
 ['2019 ', ' 2024'],
 ['2019 ', ' 2025'],
 ['2013 ', ' 2023'],
 ['2018 ', ' 2021'],
 ['2017 ', ' 2021'],
 ['2015 ', ' 2022'],
 ['2018 ', ' 2021'],
 ['2016 ', ' 2023'],
 ['2020 ', ' 2022'],
 ['2019 ', ' 2022'],
 ['2014 ', ' 2021'],
 ['2020 ', ' 2023'],
 ['2015 ', ' 2021'],
 ['2012 ', ' 2021'],
 ['2013 ', ' 2021'],
 ['2019 ', ' 2023'],
 ['2019 ', ' 2021'],
 ['2011 ', ' 2021'],
 ['2018 ', ' 2021'],
 ['2014 ', ' 2022'],
 ['2019 ', ' 2021'],
 ['2019 ', ' 2022'],
 ['2019 ', ' 2021'],
 ['2018 ', ' 2023'],
 ['2015 ', ' 2021'],
 ['Free'],
 ['2018 ', ' 2025'],
 ['2019 ', ' 2024'],
 ['2015 ', ' 2023'],
 ['2015 ', ' 2023'],
 ['Free'],
 ['Free'],
 ['Free'],
 ['Free'],
 ['Free'],
 ['Free'],
 ['Free'],
 ['2019 ', ' 2024'],
 ['2014 ', ' 2024'],
 ['2017 ', ' 2023'],
 ['2019 ', ' 2024'],
 ['2016 ', ' 2025'],
 ['2018 ', ' 2023'],
 ['2019 ', ' 2025'],
 ['2015 ', ' 2025'],
 ['2016 ', ' 2024'],
 ['2018 ', ' 2023'],
 ['2019 ', ' 2024'],
 ['2019 ', ' 2024'],
 ['2019 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['2016 ', ' 2024'],
 ['2019 ', ' 2023'],
 ['Free'],
 ['2019 ', ' 2023'],
 ['2017 ', ' 2023'],
 ['2019 ', ' 2024'],
 ['2014 ', ' 2026'],
 ['2018 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['2019 ', ' 2024'],
 ['Jun 30, 2021 On Loan'],
 ['2018 ', ' 2025'],
 ['2019 ', ' 2025'],
 ['2019 ', ' 2023'],
 ['2020 ', ' 2025'],
 ['2020 ', ' 2024'],
 ['2019 ', ' 2024'],
 ['2014 ', ' 2021'],
 ['2014 ', ' 2024'],
 ['2019 ', ' 2024'],
 ['2017 ', ' 2024'],
 ['Jun 30, 2021 On Loan'],
 ['2017 ', ' 2022'],
 ['2017 ', ' 2022'],
 ['2018 ', ' 2023'],
 ['2016 ', ' 2024'],
 ['2020 ', ' 2025'],
 ['2018 ', ' 2023'],
 ['2019 ', ' 2024'],
 ['2012 ', ' 2025'],
 ['2018 ', ' 2023'],
 ['2017 ', ' 2022'],
 ['2015 ', ' 2022'],
 ['2018 ', ' 2022'],
 ['2015 ', ' 2021'],
 ['2012 ', ' 2024'],
 ['2019 ', ' 2024'],
 ['2015 ', ' 2023'],
 ['2019 ', ' 2024'],
 ['2017 ', ' 2022'],
 ['Jun 30, 2021 On Loan'],
 ['2018 ', ' 2023'],
 ['2019 ', ' 2024'],
 ['2016 ', ' 2022'],
 ['2017 ', ' 2021'],
 ['2016 ', ' 2023'],
 ['2016 ', ' 2023'],
 ['2019 ', ' 2024'],
 ['2010 ', ' 2021'],
 ['2019 ', ' 2024'],
 ['2019 ', ' 2024'],
 ['Jun 30, 2021 On Loan'],
 ['2019 ', ' 2022'],
 ['2018 ', ' 2023'],
 ['2018 ', ' 2023'],
 ['2016 ', ' 2022'],
 ['2015 ', ' 2023'],
 ['2014 ', ' 2023'],
 ['2015 ', ' 2022'],
 ['2016 ', ' 2022'],
 ['2018 ', ' 2021'],
 ['2015 ', ' 2023'],
 ['2017 ', ' 2022'],
 ['2019 ', ' 2023'],
 ['Jun 30, 2021 On Loan'],
 ['2008 ', ' 2023'],
 ['2020 ', ' 2023'],
 ['2015 ', ' 2021'],
 ['2016 ', ' 2024'],
 ['2019 ', ' 2022'],
 ['2018 ', ' 2023'],
 ['2017 ', ' 2023'],
 ['2019 ', ' 2022'],
 ['2011 ', ' 2023'],
 ['2017 ', ' 2022'],
 ['2017 ', ' 2020'],
 ['2019 ', ' 2023'],
 ['2017 ', ' 2023'],
 ['2019 ', ' 2021'],
 ['2019 ', ' 2022'],
 ['2019 ', ' 2021'],
 ['2020 ', ' 2022'],
 ['2020 ', ' 2021'],
 ['2020 ', ' 2022'],
 ['2018 ', ' 2021'],
 ['2019 ', ' 2021'],
 ['2020 ', ' 2023'],
 ['2015 ', ' 2021'],
 ['2019 ', ' 2023'],
 ['2015 ', ' 2021'],
 ['2018 ', ' 2021'],
 ['2020 ', ' 2022'],
 ['2018 ', ' 2021'],
 ['2020 ', ' 2024'],
 ['2010 ', ' 2021'],
 ['2020 ', ' 2023'],
 ['2014 ', ' 2023'],
 ['2018 ', ' 2022'],
 ['2018 ', ' 2022'],
 ['2020 ', ' 2021'],
 ['2015 ', ' 2021'],
 ['2013 ', ' 2022'],
 ['2019 ', ' 2022'],
 ['2019 ', ' 2021'],
 ['2018 ', ' 2021'],
 ['2020 ', ' 2023'],
 ['2002 ', ' 2022'],
 ['2019 ', ' 2021'],
 ['2015 ', ' 2022'],
 ['2015 ', ' 2021'],
 ['2016 ', ' 2021'],
 ['Free'],
 ['2018 ', ' 2021'],
 ['Free'],
 ['Free'],
 ['Free'],
 ['2017 ', ' 2022'],
 ['Jun 30, 2021 On Loan'],
 ['2020 ', ' 2024'],
 ['2019 ', ' 2025'],
 ['2017 ', ' 2022'],
 ['2019 ', ' 2023'],
 ['2019 ', ' 2024'],
 ['2019 ', ' 2024'],
 ['2018 ', ' 2023'],
 ['2018 ', ' 2024'],
 ['2020 ', ' 2027'],
 ['2016 ', ' 2024'],
 ['2017 ', ' 2022'],
 ['2020 ', ' 2024'],
 ['2013 ', ' 2025'],
 ['2017 ', ' 2024'],
 ['2018 ', ' 2023'],
 ['2016 ', ' 2024'],
 ['2018 ', ' 2023'],
 ['2017 ', ' 2022'],
 ['2016 ', ' 2024'],
 ['2015 ', ' 2023'],
 ['2018 ', ' 2024'],
 ['2015 ', ' 2024'],
 ['2019 ', ' 2024'],
 ['2020 ', ' 2025'],
 ['2019 ', ' 2024'],
 ['2019 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['2017 ', ' 2023'],
 ['2018 ', ' 2022'],
 ['2020 ', ' 2023'],
 ['2019 ', ' 2024'],
 ['2019 ', ' 2023'],
 ['2017 ', ' 2022'],
 ['2018 ', ' 2021'],
 ['2016 ', ' 2021'],
 ['2018 ', ' 2024'],
 ['2019 ', ' 2024'],
 ['2018 ', ' 2024'],
 ['2017 ', ' 2023'],
 ['2016 ', ' 2022'],
 ['2018 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['Dec 31, 2020 On Loan'],
 ['2019 ', ' 2024'],
 ['2018 ', ' 2025'],
 ['2019 ', ' 2023'],
 ['Jun 30, 2021 On Loan'],
 ['2016 ', ' 2025'],
 ['2019 ', ' 2023'],
 ['2018 ', ' 2022'],
 ['2014 ', ' 2023'],
 ['2020 ', ' 2025'],
 ['2020 ', ' 2024'],
 ['2020 ', ' 2025'],
 ['2018 ', ' 2022'],
 ['2014 ', ' 2024'],
 ['2018 ', ' 2023'],
 ['2017 ', ' 2023'],
 ['2011 ', ' 2021'],
 ['2018 ', ' 2022'],
 ['2018 ', ' 2024'],
 ['2019 ', ' 2023'],
 ['2015 ', ' 2022'],
 ['2019 ', ' 2023'],
 ['Free'],
 ['2020 ', ' 2025'],
 ['2016 ', ' 2023'],
 ['2018 ', ' 2022'],
 ['2013 ', ' 2022'],
 ['2017 ', ' 2024'],
 ['2015 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['2020 ', ' 2024'],
 ['2019 ', ' 2024'],
 ['2018 ', ' 2023'],
 ['Jun 30, 2021 On Loan'],
 ['2020 ', ' 2025'],
 ['2018 ', ' 2024'],
 ['2020 ', ' 2025'],
 ['2019 ', ' 2024'],
 ['2019 ', ' 2020'],
 ['2020 ', ' 2022'],
 ['2020 ', ' 2023'],
 ['2017 ', ' 2021'],
 ['2020 ', ' 2025'],
 ['2018 ', ' 2022'],
 ['2020 ', ' 2024'],
 ['2015 ', ' 2022'],
 ['2017 ', ' 2021'],
 ['2014 ', ' 2023'],
 ['2020 ', ' 2025'],
 ['2019 ', ' 2023'],
 ['2011 ', ' 2022'],
 ['2010 ', ' 2022'],
 ['2017 ', ' 2023'],
 ['2011 ', ' 2025'],
 ['2015 ', ' 2022'],
 ['2018 ', ' 2025'],
 ['2017 ', ' 2021'],
 ['2019 ', ' 2023'],
 ['2020 ', ' 2023'],
 ['2020 ', ' 2024'],
 ['2018 ', ' 2024'],
 ['2016 ', ' 2021'],
 ['2019 ', ' 2022'],
 ['2018 ', ' 2023'],
 ['2019 ', ' 2022'],
 ['2014 ', ' 2022'],
 ['2020 ', ' 2023'],
 ['2019 ', ' 2024'],
 ['2016 ', ' 2021'],
 ['2017 ', ' 2022'],
 ['2017 ', ' 2022'],
 ['2018 ', ' 2024'],
 ['2016 ', ' 2021'],
 ['2019 ', ' 2022'],
 ['2019 ', ' 2024'],
 ['2014 ', ' 2023'],
 ['2018 ', ' 2022'],
 ['2017 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['2010 ', ' 2021'],
 ['2015 ', ' 2025'],
 ['2020 ', ' 2022'],
 ['2018 ', ' 2022'],
 ['2019 ', ' 2024'],
 ['2019 ', ' 2022'],
 ['2017 ', ' 2022'],
 ['2020 ', ' 2023'],
 ['2012 ', ' 2021'],
 ['2019 ', ' 2023'],
 ['2019 ', ' 2022'],
 ['2016 ', ' 2020'],
 ['2020 ', ' 2021'],
 ['Free'],
 ['2020 ', ' 2023'],
 ['2017 ', ' 2023'],
 ['2017 ', ' 2022'],
 ['2017 ', ' 2022'],
 ['2020 ', ' 2022'],
 ['2014 ', ' 2021'],
 ['2016 ', ' 2023'],
 ['2018 ', ' 2021'],
 ['2018 ', ' 2022'],
 ['2020 ', ' 2022'],
 ['2012 ', ' 2021'],
 ['2009 ', ' 2022'],
 ['2020 ', ' 2023'],
 ['2018 ', ' 2021'],
 ['2007 ', ' 2021'],
 ['2017 ', ' 2021'],
 ['2014 ', ' 2021'],
 ['2019 ', ' 2021'],
 ['2018 ', ' 2021'],
 ['2014 ', ' 2021'],
 ['2018 ', ' 2021'],
 ['2019 ', ' 2023'],
 ['2018 ', ' 2021'],
 ['2013 ', ' 2021'],
 ['2019 ', ' 2022'],
 ['2019 ', ' 2024'],
 ['2018 ', ' 2022'],
 ['2017 ', ' 2022'],
 ['2020 ', ' 2021'],
 ['2019 ', ' 2024'],
 ['2020 ', ' 2022'],
 ['2020 ', ' 2022'],
 ['2020 ', ' 2022'],
 ['2018 ', ' 2021'],
 ['2020 ', ' 2025'],
 ['Free'],
 ['2020 ', ' 2023'],
 ['2020 ', ' 2025'],
 ['Free'],
 ['2020 ', ' 2024'],
 ['Free'],
 ['2019 ', ' 2021'],
 ['2020 ', ' 2025'],
 ['2017 ', ' 2023'],
 ['2018 ', ' 2024'],
 ['2019 ', ' 2023'],
 ['2018 ', ' 2023'],
 ['2015 ', ' 2024'],
 ['2018 ', ' 2022'],
 ['2016 ', ' 2024'],
 ['2019 ', ' 2024'],
 ['2016 ', ' 2023'],
 ['2017 ', ' 2023'],
 ['2020 ', ' 2024'],
 ['2016 ', ' 2022'],
 ['2017 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['2020 ', ' 2024'],
 ['2016 ', ' 2023'],
 ['Jun 30, 2021 On Loan'],
 ['2016 ', ' 2022'],
 ['2019 ', ' 2023'],
 ['2017 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['2020 ', ' 2025'],
 ['2020 ', ' 2025'],
 ['2017 ', ' 2024'],
 ['2014 ', ' 2023'],
 ['2015 ', ' 2021'],
 ['2019 ', ' 2024'],
 ['2019 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['2018 ', ' 2021'],
 ['2019 ', ' 2024'],
 ['2019 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['2016 ', ' 2024'],
 ['2017 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['2015 ', ' 2023'],
 ['2018 ', ' 2021'],
 ['2017 ', ' 2022'],
 ['2020 ', ' 2024'],
 ['2019 ', ' 2024'],
 ['2018 ', ' 2022'],
 ['2019 ', ' 2024'],
 ['2018 ', ' 2023'],
 ['2018 ', ' 2023'],
 ['2020 ', ' 2024'],
 ['2019 ', ' 2022'],
 ['2019 ', ' 2024'],
 ['2020 ', ' 2025'],
 ['2020 ', ' 2024'],
 ['2013 ', ' 2023'],
 ['2017 ', ' 2022'],
 ['Jun 30, 2021 On Loan'],
 ['2017 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['2015 ', ' 2022'],
 ['2019 ', ' 2024'],
 ['2017 ', ' 2021'],
 ['2018 ', ' 2023'],
 ['Jun 30, 2021 On Loan'],
 ['2019 ', ' 2021'],
 ['2016 ', ' 2023'],
 ['Jun 30, 2021 On Loan'],
 ['2018 ', ' 2022'],
 ['2017 ', ' 2022'],
 ['2020 ', ' 2024'],
 ['2019 ', ' 2021'],
 ['Jun 30, 2021 On Loan'],
 ['Jun 30, 2021 On Loan'],
 ['2019 ', ' 2024'],
 ['2018 ', ' 2022'],
 ['2017 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['Jun 30, 2021 On Loan'],
 ['2016 ', ' 2024'],
 ['2019 ', ' 2023'],
 ['2016 ', ' 2023'],
 ['2017 ', ' 2024'],
 ['2017 ', ' 2022'],
 ['2017 ', ' 2023'],
 ['2019 ', ' 2024'],
 ['2019 ', ' 2022'],
 ['2015 ', ' 2021'],
 ['2018 ', ' 2023'],
 ['2019 ', ' 2021'],
 ['2020 ', ' 2026'],
 ['2020 ', ' 2024'],
 ['2018 ', ' 2022'],
 ['2020 ', ' 2025'],
 ['2018 ', ' 2022'],
 ['2018 ', ' 2021'],
 ['2017 ', ' 2022'],
 ['2016 ', ' 2023'],
 ['2020 ', ' 2022'],
 ['2016 ', ' 2022'],
 ['2016 ', ' 2021'],
 ['2019 ', ' 2024'],
 ['2020 ', ' 2023'],
 ['2013 ', ' 2024'],
 ['2017 ', ' 2025'],
 ['2018 ', ' 2023'],
 ['2019 ', ' 2024'],
 ['2019 ', ' 2023'],
 ['2011 ', ' 2022'],
 ['2017 ', ' 2022'],
 ['2019 ', ' 2021'],
 ['2020 ', ' 2022'],
 ['2019 ', ' 2023'],
 ['2018 ', ' 2022'],
 ['2020 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['2019 ', ' 2022'],
 ['2018 ', ' 2024'],
 ['Jun 30, 2021 On Loan'],
 ['2016 ', ' 2023'],
 ['Jun 30, 2021 On Loan'],
 ['2020 ', ' 2024'],
 ['2017 ', ' 2021'],
 ['2020 ', ' 2021'],
 ['2018 ', ' 2023'],
 ['2016 ', ' 2022'],
 ['2015 ', ' 2025'],
 ['2017 ', ' 2022'],
 ['2020 ', ' 2022'],
 ['2017 ', ' 2022'],
 ['2014 ', ' 2024'],
 ['2015 ', ' 2021'],
 ['2020 ', ' 2023'],
 ['2016 ', ' 2022'],
 ['2020 ', ' 2024'],
 ['2017 ', ' 2022'],
 ['2010 ', ' 2025'],
 ['2010 ', ' 2022'],
 ['2018 ', ' 2022'],
 ['Jun 30, 2021 On Loan'],
 ['2018 ', ' 2022'],
 ['2016 ', ' 2023'],
 ['2017 ', ' 2023'],
 ['2009 ', ' 2023'],
 ['2019 ', ' 2021'],
 ['2009 ', ' 2021'],
 ['2019 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['2017 ', ' 2021'],
 ['2020 ', ' 2021'],
 ['2019 ', ' 2022'],
 ['2012 ', ' 2022'],
 ['2015 ', ' 2021'],
 ['2007 ', ' 2022'],
 ['2018 ', ' 2021'],
 ['2018 ', ' 2021'],
 ['2016 ', ' 2021'],
 ['2008 ', ' 2021'],
 ['2020 ', ' 2020'],
 ['2019 ', ' 2021'],
 ['2015 ', ' 2022'],
 ['2015 ', ' 2021'],
 ['2015 ', ' 2021'],
 ['2018 ', ' 2021'],
 ['2014 ', ' 2022'],
 ['2019 ', ' 2021'],
 ['2018 ', ' 2022'],
 ['2020 ', ' 2024'],
 ['2012 ', ' 2021'],
 ['2017 ', ' 2023'],
 ['2017 ', ' 2023'],
 ['2020 ', ' 2023'],
 ['2016 ', ' 2021'],
 ['2016 ', ' 2022'],
 ['2017 ', ' 2023'],
 ['2020 ', ' 2024'],
 ['2016 ', ' 2023'],
 ['2020 ', ' 2021'],
 ['2011 ', ' 2021'],
 ['2018 ', ' 2021'],
 ['2013 ', ' 2022'],
 ['2019 ', ' 2022'],
 ['2017 ', ' 2023'],
 ['2017 ', ' 2021'],
 ['2016 ', ' 2023'],
 ['2017 ', ' 2022'],
 ['2018 ', ' 2021'],
 ['2015 ', ' 2022'],
 ['2017 ', ' 2022'],
 ['2020 ', ' 2021'],
 ['Jun 30, 2021 On Loan'],
 ['2018 ', ' 2021'],
 ['2018 ', ' 2021'],
 ['2018 ', ' 2022'],
 ['2020 ', ' 2022'],
 ['2020 ', ' 2022'],
 ['2020 ', ' 2023'],
 ['2018 ', ' 2021'],
 ['2017 ', ' 2022'],
 ['2012 ', ' 2021'],
 ['2016 ', ' 2021'],
 ['2017 ', ' 2021'],
 ['2019 ', ' 2023'],
 ['2020 ', ' 2025'],
 ['2020 ', ' 2023'],
 ['2015 ', ' 2024'],
 ['2016 ', ' 2026'],
 ['2014 ', ' 2023'],
 ['2016 ', ' 2023'],
 ['2018 ', ' 2024'],
 ['2020 ', ' 2024'],
 ['2017 ', ' 2021'],
 ['2019 ', ' 2022'],
 ['2015 ', ' 2025'],
 ['2020 ', ' 2024'],
 ['2018 ', ' 2021'],
 ['2019 ', ' 2024'],
 ['2019 ', ' 2024'],
 ['2020 ', ' 2021'],
 ['2020 ', ' 2025'],
 ['2020 ', ' 2024'],
 ['2020 ', ' 2022'],
 ['2018 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['2011 ', ' 2021'],
 ['2016 ', ' 2022'],
 ['2019 ', ' 2023'],
 ['2014 ', ' 2021'],
 ['Jun 30, 2021 On Loan'],
 ['2020 ', ' 2022'],
 ['2017 ', ' 2022'],
 ['2019 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['2017 ', ' 2023'],
 ['2017 ', ' 2021'],
 ['Jun 30, 2021 On Loan'],
 ['2016 ', ' 2024'],
 ['Free'],
 ['2015 ', ' 2022'],
 ['2019 ', ' 2022'],
 ['2020 ', ' 2023'],
 ['2016 ', ' 2024'],
 ['2020 ', ' 2024'],
 ['2017 ', ' 2021'],
 ['2017 ', ' 2023'],
 ['2017 ', ' 2022'],
 ['2011 ', ' 2023'],
 ['2019 ', ' 2023'],
 ['2017 ', ' 2024'],
 ['2016 ', ' 2022'],
 ['2019 ', ' 2023'],
 ['2019 ', ' 2022'],
 ['2020 ', ' 2025'],
 ['2019 ', ' 2024'],
 ['2019 ', ' 2023'],
 ['2017 ', ' 2021'],

On inspection of the resulting array, I can see that there are 3 different styles of values in the "contract" column:

* date range values
* "On Loan" values
* Free

Time for a closer look of the latter styles

In [72]:
# View rows with "On Loan" values

rawfifa[rawfifa['contract'].str.contains("On Loan")][['contract', 'joined', 'loan_date_end',]]

                   contract     joined loan_date_end
205    Jun 30, 2021 On Loan 2013-09-01    2021-06-30
248    Jun 30, 2021 On Loan 2010-07-01    2021-06-30
254    Jun 30, 2021 On Loan 2015-07-02    2021-06-30
302    Jun 30, 2021 On Loan 2019-07-01    2021-06-30
306    Jun 30, 2021 On Loan 2018-07-12    2021-06-30
...                     ...        ...           ...
18472  Aug 31, 2021 On Loan 2018-02-13    2021-08-31
18571  Jun 30, 2021 On Loan 2019-07-12    2021-06-30
18600  Dec 31, 2020 On Loan 2017-07-14    2020-12-31
18622  Dec 31, 2020 On Loan 2019-07-25    2020-12-31
18680  Dec 31, 2020 On Loan 2016-01-01    2020-12-31

[1013 rows x 3 columns]

This subset shows me that the "contract" column does not hold the start date for loan contracts. However, this date can be gotten from the "joined" column

In [70]:
# View rows with "Free" values

rawfifa[rawfifa['contract'].str.contains("Free")][['contract', 'joined', 'loan_date_end', 'club']]

      contract     joined loan_date_end     club
289       Free 2019-01-01           NaT  No Club
292       Free 2019-01-01           NaT  No Club
369       Free 2018-08-10           NaT  No Club
374       Free 2018-08-10           NaT  No Club
375       Free 2018-08-10           NaT  No Club
...        ...        ...           ...      ...
17220     Free 2018-07-01           NaT  No Club
17343     Free 2019-07-12           NaT  No Club
17659     Free 2019-07-12           NaT  No Club
17661     Free 2019-07-12           NaT  No Club
18205     Free 2019-07-12           NaT  No Club

[237 rows x 4 columns]

I have added the 'club' column to this subset and it confirms that this value represents those without a club contract.

This means the values in the "joined" column for these rows are irrelevant.

With this, I believe the best course of action is to:

* break up the "contract" col into "contract_start" and "contract_end" columns
* loan start and end years will be gotten from the "joined" and "loan_date_end" col respectively.
* all free values will be recorded as nans for both start and end
* drop joined col
* turn loan col to bool column

In [73]:
# Save point

rawfifa.to_csv(r"C:\Users\T. Barnes\Documents\Data Science\DataCleaningChallenge\Working_on\rawfifa_sun.csv", index=False)

# To be continued...